# Generated by Django 3.2.4 on 2021-06-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210628_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, default=[], null=True, related_name='tags', to='api.Tag'),
        ),
    ]
