# Generated by Django 3.2.4 on 2021-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
